#!/bin/sh
# 
# Author: ydalton

# Bail if any undeclared variables are used
set -u

INVOKED_NAME=$(basename $0)

usage() {
	echo "usage: $INVOKED_NAME FILE"
	exit $1
}

# Check if there is the first argument
[ -z ${1+x} ] && usage 1

# Check if the argument exists as a file
if [ ! -f "$1" ]; then
	echo "No such file $1."
	exit 1 
fi

TEMP_FILE=$(mktemp)

# Add shebang, and required HTTP header plus newline
cat << EOF >> $TEMP_FILE
#!/bin/bash
echo "Content-Type: text/html"
echo 
EOF

tail -n +2 $1 | awk '
	# add shebang and 
	BEGIN {
		print "cat << EOF"
		printstr=1
	}; 
	/\$\{/&&/\}/{
		gsub("{", "(");
		gsub("}", ")");
		print
		next
	};
	/\$\{/{
		print "EOF"
		printstr=0
	};
	/\}/ {
		printstr=1
		print "cat << EOF"
		next
	};
	{
		if(printstr)
			print
		else 
			printstr=1
	};
	END {
		print "EOF"
	};
' >> $TEMP_FILE
[ ! -z ${SHTML_DEBUG+x} ] && sed 's/^/# /g' $TEMP_FILE
chmod +x $TEMP_FILE
# Run the file
$TEMP_FILE
rm $TEMP_FILE
